# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
port: 3000
safe: true
gems: [jekyll-paginate]

# edit here to achieve your personal greatness
url: http://me.xuzhang.work/
baseurl: http://me.xuzhang.work/
title: Zhang Xu
author: Zhang Xu
description: Personal blog and resume
avatar: profile.png
email: xzhcn6@outlook.com
github: xzhcn6
twitter: Snake_Shawn
linkedin: xu-zhang-613b33b7
disqus: username
google_analytics: UA-69391421-1
